SI-Projekt/SI-Projekt-Anamnese-Service

src/main/java/thb/siprojektanamneseservice/model/Diagnosis.java
src/main/java/thb/siprojektanamneseservice/model/Disease.java
src/main/java/thb/siprojektanamneseservice/model/FamilyAnamnesis.java
src/main/java/thb/siprojektanamneseservice/model/Patient.java
src/main/java/thb/siprojektanamneseservice/model/VegetativeAnamnesis.java
src/main/java/thb/siprojektanamneseservice/model/constants/AllergyType.java
src/main/java/thb/siprojektanamneseservice/model/constants/Examinations.java
src/main/java/thb/siprojektanamneseservice/model/constants/Gender.java
src/main/java/thb/siprojektanamneseservice/model/constants/MaritalStatus.java
src/main/java/thb/siprojektanamneseservice/model/constants/PreExistingIllness.java
src/main/java/thb/siprojektanamneseservice/model/constants/VegetativeAnamnesisDecision.java

@MistraForest  @steve2christ  @Astrid237  @Juvniele 
Package structur change

Package Constant added

---

src/main/java/thb/siprojektanamneseservice/service/PatientService.java

@MistraForest  @steve2christ  
CRUD for Patient

PatientService CRUD created

---

src/main/java/thb/siprojektanamneseservice/repository/MedicationInTakeRepository.java
src/main/java/thb/siprojektanamneseservice/rest/ApiConstants.java
src/main/java/thb/siprojektanamneseservice/rest/medicationIntake/MedicationInTakeItemController.java
src/main/java/thb/siprojektanamneseservice/rest/medicationIntake/MedicationInTakeRootController.java
src/main/java/thb/siprojektanamneseservice/service/MedicationInTakeService.java
src/main/resources/application.properties

@steve2christ  Endpoint created

Endpoint MedicationInTake created

---

src/main/java/thb/siprojektanamneseservice/repository/PreExistingIllnessRepository.java
src/main/java/thb/siprojektanamneseservice/rest/ApiConstants.java
src/main/java/thb/siprojektanamneseservice/rest/preExistingIllness/PreExistingIllnessItemController.java
src/main/java/thb/siprojektanamneseservice/rest/preExistingIllness/PreExistingIllnessRootController.java
src/main/java/thb/siprojektanamneseservice/service/PreExistingIllnessService.java

Endpoint PreExistingIllness created

---

src/main/java/thb/siprojektanamneseservice/repository/MaritalStatusRepository.java
src/main/java/thb/siprojektanamneseservice/rest/ApiConstants.java
src/main/java/thb/siprojektanamneseservice/rest/maritalStatus/MaritalStatusItemController.java
src/main/java/thb/siprojektanamneseservice/rest/maritalStatus/MaritalStatusRootController.java
src/main/java/thb/siprojektanamneseservice/service/MaritalStatusService.java

Issue 20 create endpoint for marital status

---

src/main/java/thb/siprojektanamneseservice/repository/AllergyTypeRepository.java
src/main/java/thb/siprojektanamneseservice/rest/ApiConstants.java
src/main/java/thb/siprojektanamneseservice/rest/allergyType/AllergyTypeItemController.java
src/main/java/thb/siprojektanamneseservice/rest/allergyType/AllergyTypeRootController.java
src/main/java/thb/siprojektanamneseservice/service/AllergyTypeService.java

Endpoint AllergyType created

---

src/main/java/thb/siprojektanamneseservice/repository/DiagnosisRepository.java
src/main/java/thb/siprojektanamneseservice/rest/ApiConstants.java
src/main/java/thb/siprojektanamneseservice/rest/diagnosis/DiagnosisItemController.java
src/main/java/thb/siprojektanamneseservice/rest/diagnosis/DiagnosisRootController.java
src/main/java/thb/siprojektanamneseservice/service/DiagnosisService.java

Issue 14 create endpoint for diagnosis

---

src/main/java/thb/siprojektanamneseservice/repository/VegetativeAnamnesisRepository.java
src/main/java/thb/siprojektanamneseservice/rest/ApiConstants.java
src/main/java/thb/siprojektanamneseservice/rest/vegetativeAnamnesis/VegetativeAnamnesisItemController.java
src/main/java/thb/siprojektanamneseservice/rest/vegetativeAnamnesis/VegetativeAnamnesisRootController.java
src/main/java/thb/siprojektanamneseservice/service/VegetativeAnamnesisService.java

endpoint for vegetativeAnamnesis created

---

src/main/java/thb/siprojektanamneseservice/repository/FamilyAnamnesisRepository.java
src/main/java/thb/siprojektanamneseservice/rest/ApiConstants.java
src/main/java/thb/siprojektanamneseservice/rest/familyAnamnesis/FamilyAnamnesisItemController.java
src/main/java/thb/siprojektanamneseservice/rest/familyAnamnesis/FamilyAnamnesisRootController.java
src/main/java/thb/siprojektanamneseservice/service/FamilyAnamnesisService.java

endpoint for family anamnesis created

---

src/main/java/thb/siprojektanamneseservice/repository/DiseaseRepository.java
src/main/java/thb/siprojektanamneseservice/rest/ApiConstants.java
src/main/java/thb/siprojektanamneseservice/rest/disease/DiseaseItemController.java
src/main/java/thb/siprojektanamneseservice/rest/disease/DiseaseRootController.java
src/main/java/thb/siprojektanamneseservice/service/DiseaseService.java

endpoint for disease created

---

src/main/java/thb/siprojektanamneseservice/repository/VegetativeAnamnesisDecisionRepository.java
src/main/java/thb/siprojektanamneseservice/rest/ApiConstants.java
src/main/java/thb/siprojektanamneseservice/rest/vegetativeAnamnesisDecision/VegetativeAnamnesisDecisionItemController.java
src/main/java/thb/siprojektanamneseservice/rest/vegetativeAnamnesisDecision/VegetativeAnamnesisDecisionRootController.java
src/main/java/thb/siprojektanamneseservice/service/VegetativeAnamnesisDecisionService.java

endpoint for vegetative anamnesis decision created

---

src/main/java/thb/siprojektanamneseservice/repository/GenderRepository.java
src/main/java/thb/siprojektanamneseservice/rest/ApiConstants.java
src/main/java/thb/siprojektanamneseservice/rest/gender/GenderItemController.java
src/main/java/thb/siprojektanamneseservice/rest/gender/GenderRootController.java
src/main/java/thb/siprojektanamneseservice/service/GenderService.java

endpoint for gender created

---

src/main/java/thb/siprojektanamneseservice/repository/ExaminationRepository.java
src/main/java/thb/siprojektanamneseservice/rest/ApiConstants.java
src/main/java/thb/siprojektanamneseservice/rest/examination/ExaminationItemController.java
src/main/java/thb/siprojektanamneseservice/rest/examination/ExaminationRootController.java
src/main/java/thb/siprojektanamneseservice/service/ExaminationService.java

endpoint for examination created

---

src/main/java/thb/siprojektanamneseservice/service/PatientService.java

@MistraForest
Number changed to id in PatientService.java

Number changed to id in PatientService.java

---

pom.xml
src/main/java/thb/siprojektanamneseservice/model/Person.java
src/main/java/thb/siprojektanamneseservice/transfert/PersonTO.java
src/main/resources/application.properties
src/test/java/thb/siprojektanamneseservice/service/AddressServiceTest.java
src/test/java/thb/siprojektanamneseservice/service/PersonServiceTest.java
src/test/resources/application.properties

@steve2christ  Unit test done for Person and Address

Person and address unit tests done!

---

src/main/java/thb/siprojektanamneseservice/service/AllergyService.java
src/test/java/thb/siprojektanamneseservice/service/AllergyServiceTest.java

Unit test for service Allergy done

---

src/test/java/thb/siprojektanamneseservice/service/IllnessServiceTest.java

Unit test for service Illness done

---

src/test/java/thb/siprojektanamneseservice/service/IllnessServiceTest.java
src/test/java/thb/siprojektanamneseservice/service/SecurityServiceTest.java

Unit test for service Security done

---

.travis.yml
src/test/java/thb/siprojektanamneseservice/service/SecurityServiceTest.java

@steve2christ problem, can't automaticaly merge!

Issue 49 create unit test for security service

---

src/test/java/thb/siprojektanamneseservice/service/MedicationInTakeServiceTest.java

Unit test for service MedicationInTake done

---

src/test/java/thb/siprojektanamneseservice/service/FamilyAnamnesisServiceTest.java

Unit test for service FamilyAnamnasis done

---

src/test/java/thb/siprojektanamneseservice/service/VegetativeAnamnesisServiceTest.java

unit test done!

---

pom.xml
src/main/java/thb/siprojektanamneseservice/model/Person.java
src/main/java/thb/siprojektanamneseservice/rest/address/AddressRootController.java
src/test/java/thb/siprojektanamneseservice/rest/AddressControllerIT.java
src/test/java/thb/siprojektanamneseservice/rest/AllergyControllerIT.java
src/test/java/thb/siprojektanamneseservice/rest/DiagnosisControllerIT.java
src/test/java/thb/siprojektanamneseservice/rest/SecurityControllerIT.java
src/test/resources/application-test.properties
src/test/resources/application.properties

Issue 62 create some integration tests

---

.travis.yml
appspec.yml
scripts/runapp.sh
scripts/startappsilent.sh
scripts/utilities.sh
src/main/resources/application.properties

Merge pull request should triggert deployement on aws

Issue 70 clean up

---

Si-Projekt-doku.md
src/main/java/thb/siprojektanamneseservice/rest/ApiConstants.java

Fix connection frontend and backend in aws
